application: bookedbybits
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/css
  static_dir: static/css
 
- url: /static/images
  static_dir: static/images

- url: /static/js
  static_dir: static/js
 
- url: .*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
