application: bookedbybits
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/css
  static_dir: static/css
 
- url: /static/images
  static_dir: static/images
 #upload: static/.*\.(gif|png|jpg)$
 
#- url: /static/images(.*\.jpg)$
#  static_dir: /static/images/\1
#  upload: /static/images/.*\.jpg$
#  mime_type: "image/jpeg"
 
- url: .*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
